### ISSUE TITLE
Should we version the schema?

### ISSUE THREAD

**Issue by ApiSecRay** [restful-api-description-language/RADL#13]
Do we need a `version` attribute on the `service` element, or a version indication in the RADL namespace URI?

**Comment by gentlewind** [comment]
Is it a version label for the RADL schema or the version label for the designed RADL document? They are two different problems.

**Comment by ApiSecRay** [comment]
I meant the RADL schema.

I don't see much value in a version on the designed service, since you'd most likely store it in version control anyway. I guess if you make breaking changes to your API it *might* be useful to have a version.
