### ISSUE TITLE
Default media type

### ISSUE THREAD

**Issue by ApiSecRay** [restful-api-description-language/RADL#14]
If an API uses a single media type for most of its messages, it's quite annoying that it must repeat that over and over again.

Currently, the schema allows this:

    <method name="GET">
      <response>
        <representations/>
      </response>
    </method>

We could decide that that means it returns the only defined media type, but it doesn't look very elegant...

**Comment by gentlewind** [comment]
It's helpful to return the only defined media type for such a case.

**Comment by ApiSecRay** [comment]
I'm not sure I understand. Do you mean the following?

    <method name="GET">
      <response>
        <representations>
          <representation media-type="application/ld+json"/>
        </representations>
      </response>
    </method>

All methods of all resources will look like that. Simply repeating something over and over again isn't adding any information, only noise.

**Comment by gentlewind** [comment]
Sorry for the confusion! I meant to say I agree that it is helpful to **ignore** the only defined media type.

**Comment by ApiSecRay** [comment]
* RAML has a [default media type](http://raml.org/spec.html#default-media-type).
* Swagger has a default as well, but splits it up into [`consumes` and `produces`](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#swagger-object)

**Comment by jonathanrobie** [comment]
This is a common use case, I agree that this is a good idea, and I will add it to the schema.

**Comment by jonathanrobie** [comment]
There are at least three ways we could do this.

1. If <media-types> contains only one media type, it is automatically treated as the default media type.  This is simpler in the very common case where only one media type is ever used, and requires no change to the schema (but does require changes to the stylesheet).
2. Add a default attribute:  <media-types default="application/ld+json"/>, where the value is the name of a media type.  This is simpler in the case where there are multiple media types but most messages use a given media type.
3. Add a default attribute, but require it only if more than one media type is present.

Which do you prefer?

**Comment by ApiSecRay** [comment]
I like 3 best.

I take it the proposed `default` attribute will be on the `media-types` element?

**Comment by jonathanrobie** [comment]
Yes, the `default` attribute will be on the `media-types` element.

**Comment by ApiSecRay** [comment]
We could go with a `default` attribute on `<media-type>` and if it's not set then treat the first media type as default. That looks nice for the case there is only one media type, but also works well for when there are several.

**Comment by gentlewind** [comment]
+1

**Comment by jonathanrobie** [comment]
I don't like treating the first media type as default.  The meaning should
not depend on the order.

I think I would like to see the default media type in the media-types
element:

<media-types default="text/html"/>

**Comment by ApiSecRay** [comment]
+1

**Comment by gentlewind** [comment]
+1
