### ISSUE TITLE
Add <specification> to <link-relation>

### ISSUE THREAD

**Issue by ApiSecRay** [restful-api-description-language/RADL#15]
Just like media types, link relations can be documented in a specification, so it makes sense to express that in RADL. Currently, you have to use a `<radl:documentation>` element with an `<html:a href="...">` or `<ref uri="...">`.

**Comment by ApiSecRay** [comment]
Also, what about status codes, headers, and URI query parameters?

**Comment by jonathanrobie** [comment]
+1 for all elements mentioned in the first two comments.

**Comment by ApiSecRay** [comment]
Status codes are fixed by the schema, so those don't make sense. +1 on the others.

**Comment by gentlewind** [comment]
+1
