### ISSUE TITLE
transitions missing from generated documentation in v1.0.10

### ISSUE THREAD

**Issue by julian-hj** [restful-api-description-language/RADL#20]
The resources documentation shows a section for transitions corresponding to each method on a resource, but fails to pick up the reference from the .radl file, even though it passes validation.  Maybe this is a residual effect of the change from name to ref in the transition reference? This was working in the 1.0.0 version, before that change went in.

**Comment by jonathanrobie** [comment]
Yes, I forgot to change that when we changed the schema. I'll fix it ...
