### ISSUE TITLE
Have methods in state transitions table link to resource method

### ISSUE THREAD

**Issue by ApiSecRay** [restful-api-description-language/RADL#29]
In the documentation for a state there is a table of transitions, which includes a column for the method. The values in that column should link to the method under the resource.

**Comment by jonathanrobie** [comment]
I'm fixing that now. 

Note that the transition name in the table (first column) already links to the implementation of the transition (e.g. "Transition: find type"), where the HTTP method is the entry in the first bullet point:

![image](https://cloud.githubusercontent.com/assets/1767869/8530452/09403bf4-23ef-11e5-8272-a9955d2926b6.png)

Unless there's a reason to do something different, I'm going to make the HTTP method link to the same place as the transition name.  I do agree it's an obvious place to want to click.  Anyone using HTML generated by an existing stylesheet can just click on the transition name.
