### ISSUE TITLE
Remove duplicate documentation for URI template variables

### ISSUE THREAD

**Issue by ApiSecRay** [restful-api-description-language/RADL#30]
Assume the RESTBucks service. We'd have an order at `/orders/{order-id}/`, payments for the order at `/orders/{order-id}/payments/`, the receipt at `/orders/{order-id}/receipt/`, and the serving at `/orders/{order-id}/serving/`. With the current schema, you'd have to document the `order-id` URI template variable **four times**.

(It seems that [Swagger](http://petstore.swagger.io/) suffers from the same problem.)

I see at least the following ways to get rid of this duplication:

1. Document the URI template variables once under `<service-conventions>` and turn `<var>` into a reference.
1. Capture the parent-child relationships between `<resource>` elements, for instance using a `parent` attribute, or using nesting (which is what [RAML](http://raml.org/index.html) seems to be doing).

**Comment by gentlewind** [comment]
The URI templates could be strucuted, but resources are not. So I do not think method (2) is good. Is it possible to make the <location> independent of <resource> and make it extensible?

**Comment by ApiSecRay** [comment]
Resources are -by definition- identified by URIs. So if two URIs have a parent/child relationship, so must the resources identified by those URIs. Otherwise the resources aren't properly named.

**Comment by gentlewind** [comment]
It's right that the two resources probably have the implicit relationship when their URIs derive from the same path prefix, e.g. a document resource, and a version-history resource. But the two resources should not be taken as parent-child relationship on the REST level. For example, version-history resource can exist & be discoverable independently without the exposure of document resource (though odd). So I am nervous about building parent-child relationship for `<resource>`.

**Comment by jonathanrobie** [comment]
+1

**Comment by ApiSecRay** [comment]
In summary: we don't want option 2, since we don't want the value of the `uri-template` to affect the layout of the `resource` elements.
The proposal is option 1: move `var` under `service-conventions`. Note that this is a breaking change.

**Comment by gentlewind** [comment]
+1

**Comment by jonathanrobie** [comment]
+1
