### ISSUE TITLE
Extract common data structure out of <data-model>

### ISSUE THREAD

**Issue by ApiSecRay** [restful-api-description-language/RADL#32]
Consider a system for working with people and organizations they are affiliated with. There would be resources `/organizations/{id}/` and `/persons/{id}/` and the representation for both would include an address. With the current schema, we would have two `<data-model>` elements that contain nested properties for the address. IOW, we would have to duplicate the address structure.

I propose we eliminate that duplication by introducing a reference, e.g. something like:

    <data-model name="address">
      
    </data-model>

    <data-model name="person">
      <properties>
        <property name="address">
          <properties ref="address"/>
        </property>
      </properties>
    </data-model>

    <data-model name="organization">
      <properties>
        <property name="visit-address">
          <properties ref="address"/>
        </property>
        <property name="post-address">
          <properties ref="address"/>
        </property>
      </properties>
    </data-model>

**Comment by jonathanrobie** [comment]
+1

**Comment by gentlewind** [comment]
+1 for `ref`

**Comment by jonathanrobie** [comment]
Note that this is a breaking change for anyone using data models.

**Comment by ApiSecRay** [comment]
Why is that? We're just adding the `ref` attribute, not taking anything away or changing any existing semantics, are we?

**Comment by jonathanrobie** [comment]
The `ref`  attribute by itself is not a breaking change, we have several related issues, and the  `data-model` element is going away.

**Comment by jonathanrobie** [comment]
See https://github.com/restful-api-description-language/RADL/issues/34

**Comment by jonathanrobie** [comment]
Is this resolved by the solution in issue #34 ?

**Comment by ApiSecRay** [comment]
Yes.
