### ISSUE TITLE
Add status to <error> element

### ISSUE THREAD

**Issue by ApiSecRay** [restful-api-description-language/RADL#42]
Should we add a `status` attribute to the `error` element?

This is not so much for clients, who shouldn't tightly couple to status codes, but more for servers. For instance, we could use this information to generate exception classes and a central exception-to-status mapper.

Here's an example error condition for RESTBucks:

    <error name="http://errors.restbucks.com/invalid-item" status="400">
      <documentation>
        The attributes you provided are invalid for the requested menu item.
      </documentation>
    </error>

And here's the Spring code we could generate from that:

    /**
     * The attributes you provided are invalid for the requested menu item.
     */
    public class InvalidItemException extends IllegalArgumentException {

      public InvalidItemException() {
        super("http://errors.restbucks.com/invalid-item");
      }

    }

    @ControllerAdvice
    public class CentralErrorHandler {

      @ExceptionHandler({ IllegalArgumentException.class })
      public ResponseEntity<String> illegalArgument(IllegalArgumentException e) {
        return new ResponseEntity<String>(e.getMessage(), HttpStatus.BAD_REQUEST);
      }

    }

Without the `status` attribute, we wouldn't know what base class to generate for `InvalidItemException`.

**Comment by ApiSecRay** [comment]
See also #39.

**Comment by jonathanrobie** [comment]
The use case makes sense.  Three questions / suggestions:

- I assume this would be an optional attribute?
- Could the same error be used with more than one status code?
- In the rest of our schema, a status attribute indicates the status of the implementation.  Perhaps `status-code` would be a better name for this attribute?

**Comment by ApiSecRay** [comment]
Yes. No. OK.

**Comment by ApiSecRay** [comment]
The proposal is:

    error = element error { name, error-status-code?, documentation* }
    error-status-code = attribute status-code { HTTP-status-enum }

**Comment by jonathanrobie** [comment]
Let's leave the issue open until William responds, but I'll add it to the
schema right now.

**Comment by gentlewind** [comment]
+1
