### ISSUE TITLE
Write RADL for extended REST Services

### ISSUE THREAD

**Issue by gentlewind** [restful-api-description-language/RADL#49]
Saying that the company ACME publishes a ACME Core REST Services with RADL documentation. Its customer extends the ACME REST Services and needs to document additional REST APIs into the RADL. There are several means to do this:
* Modify the Core RADL directly, and re-generate the HTML doc.
* Write the standalone RADL for the extended services, and merge with Core RADL by RADL Tool.

The latter approach has the advantage:
* it won't break or manipulate Core RADL
* it brings the opportunity to let multiple extended REST Services work together to build the entire & catorizied REST documentation

**Comment by ApiSecRay** [comment]
How is this issue different from #35?

**Comment by gentlewind** [comment]
Sorry, they are duplicated:) Let me close this one.
